name: GH Event Debugging

on:
  push:
    paths-ignore:
      - ".github/workflows/**"

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:

      - name: Events
        run: |
          echo "Github Event: ${{ github.event }}"
          echo "Github Event Name: ${{ github.event_name }}"
          echo "Github Event Path: ${{ github.event_path }}"
          echo "Github Event Ref: ${{ github.event.ref }}"
          echo "Github Event Base-Ref: ${{ github.event.base_ref }}"
          echo "Github Event After: ${{ github.event.after }}"
          echo "Github Event Before: ${{ github.event.before }}"
          echo "Github Event Commits: ${{ github.event.commits }}"
          echo "Github Event Compare: ${{ github.event.compare }}"
          for entry in "${{ github.event.commits }}"
            do
              echo "$entry"
            done

      - id: files
        uses: jitterbit/get-changed-files@v1
      - run: |
          for changed_file in ${{ steps.files.outputs.all }}; do
            echo "Do something with this ${changed_file}."
          done