name: GH Event Debugging

on:
  push:
    paths-ignore:
      - ".github/workflows/**"

jobs:
  Debug:
    runs-on: ubuntu-latest
    outputs:
      filenames: ${{ steps.files.outputs.added_modified }} # array of files changed by commit who triggered the workflow
    steps:
      - name: Get Files that Changed
        id: files
        uses: masesgroup/retrieve-changed-files@v2
        with:
          format: 'json'


  Do-Something-For-Each:
    needs: Debug
    continue-on-error: true # if one team fails, the flow should continue
    strategy:
      #max-parallel: 1
      matrix:
        changed-file: ${{fromJSON(needs.Debug.outputs.filenames)}}
    runs-on: ubuntu-latest
    steps:
          - name: Name the file
            run: |
                echo "Change detected for: ${{matrix.changed-file}}"