name: GH Event Debugging

on:
  push:
    paths-ignore:
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Run a one-line script
        run: |
          echo "${{ github.event.action }}"

